# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Thasadith")
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color:rgb(1, 29, 59)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.LogRegPage = QtWidgets.QWidget()
        self.LogRegPage.setStyleSheet("backcolor: red\n"
"")
        self.LogRegPage.setObjectName("LogRegPage")
        self.TitleLabel = QtWidgets.QLabel(self.LogRegPage)
        self.TitleLabel.setGeometry(QtCore.QRect(395, 30, 491, 161))
        font = QtGui.QFont()
        font.setFamily("Barbaro")
        font.setPointSize(72)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setStyleSheet("color: rgb(83, 203, 189)")
        self.TitleLabel.setWordWrap(False)
        self.TitleLabel.setObjectName("TitleLabel")
        self.tabWidget = QtWidgets.QTabWidget(self.LogRegPage)
        self.tabWidget.setGeometry(QtCore.QRect(160, 250, 961, 441))
        font = QtGui.QFont()
        font.setFamily("Staatliches")
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.LoginTab = QtWidgets.QWidget()
        self.LoginTab.setObjectName("LoginTab")
        self.UsernameInput = QtWidgets.QLineEdit(self.LoginTab)
        self.UsernameInput.setGeometry(QtCore.QRect(240, 20, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Staatliches")
        font.setPointSize(24)
        self.UsernameInput.setFont(font)
        self.UsernameInput.setStyleSheet("border: 1px solid rgb(107, 107, 107); \n"
"color: white;")
        self.UsernameInput.setObjectName("UsernameInput")
        self.PasswordInput = QtWidgets.QLineEdit(self.LoginTab)
        self.PasswordInput.setGeometry(QtCore.QRect(240, 70, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Staatliches")
        font.setPointSize(24)
        self.PasswordInput.setFont(font)
        self.PasswordInput.setStyleSheet("border: 1px solid rgb(107, 107, 107); \n"
"color: white;")
        self.PasswordInput.setObjectName("PasswordInput")
        self.LoginButton = QtWidgets.QPushButton(self.LoginTab)
        self.LoginButton.setGeometry(QtCore.QRect(330, 310, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Staatliches")
        font.setPointSize(26)
        self.LoginButton.setFont(font)
        self.LoginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoginButton.setStyleSheet("color: white;\n"
"background-color: rgb(83, 203, 189)")
        self.LoginButton.setCheckable(False)
        self.LoginButton.setAutoDefault(False)
        self.LoginButton.setDefault(False)
        self.LoginButton.setFlat(False)
        self.LoginButton.setObjectName("LoginButton")
        self.ForgotButton = QtWidgets.QPushButton(self.LoginTab)
        self.ForgotButton.setGeometry(QtCore.QRect(340, 380, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setUnderline(True)
        self.ForgotButton.setFont(font)
        self.ForgotButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ForgotButton.setStyleSheet("color: rgba(111, 111, 111, 100);\n"
"background-color: rgba(255, 255, 255, 0)")
        self.ForgotButton.setCheckable(False)
        self.ForgotButton.setAutoDefault(False)
        self.ForgotButton.setDefault(False)
        self.ForgotButton.setFlat(False)
        self.ForgotButton.setObjectName("ForgotButton")
        self.IPInput = QtWidgets.QLineEdit(self.LoginTab)
        self.IPInput.setGeometry(QtCore.QRect(240, 120, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Staatliches")
        font.setPointSize(24)
        self.IPInput.setFont(font)
        self.IPInput.setStyleSheet("border: 1px solid rgb(107, 107, 107); \n"
"color: white;")
        self.IPInput.setObjectName("IPInput")
        self.tabWidget.addTab(self.LoginTab, "")
        self.RegisterTab = QtWidgets.QWidget()
        self.RegisterTab.setObjectName("RegisterTab")
        self.UsernameInput2 = QtWidgets.QLineEdit(self.RegisterTab)
        self.UsernameInput2.setGeometry(QtCore.QRect(240, 20, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Staatliches")
        font.setPointSize(24)
        self.UsernameInput2.setFont(font)
        self.UsernameInput2.setStyleSheet("border: 1px solid rgb(107, 107, 107); \n"
"color: white;")
        self.UsernameInput2.setObjectName("UsernameInput2")
        self.PasswordInput2 = QtWidgets.QLineEdit(self.RegisterTab)
        self.PasswordInput2.setGeometry(QtCore.QRect(240, 70, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Staatliches")
        font.setPointSize(24)
        self.PasswordInput2.setFont(font)
        self.PasswordInput2.setStyleSheet("border: 1px solid rgb(107, 107, 107); \n"
"color: white;")
        self.PasswordInput2.setObjectName("PasswordInput2")
        self.NicknameInput = QtWidgets.QLineEdit(self.RegisterTab)
        self.NicknameInput.setGeometry(QtCore.QRect(240, 120, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Staatliches")
        font.setPointSize(24)
        self.NicknameInput.setFont(font)
        self.NicknameInput.setStyleSheet("border: 1px solid rgb(107, 107, 107); \n"
"color: white;")
        self.NicknameInput.setObjectName("NicknameInput")
        self.RegisterButton = QtWidgets.QPushButton(self.RegisterTab)
        self.RegisterButton.setGeometry(QtCore.QRect(330, 330, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Staatliches")
        font.setPointSize(26)
        self.RegisterButton.setFont(font)
        self.RegisterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RegisterButton.setStyleSheet("color: white;\n"
"background-color: rgb(83, 203, 189)")
        self.RegisterButton.setCheckable(False)
        self.RegisterButton.setAutoDefault(False)
        self.RegisterButton.setDefault(False)
        self.RegisterButton.setFlat(False)
        self.RegisterButton.setObjectName("RegisterButton")
        self.IPInput2 = QtWidgets.QLineEdit(self.RegisterTab)
        self.IPInput2.setGeometry(QtCore.QRect(240, 170, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Staatliches")
        font.setPointSize(24)
        self.IPInput2.setFont(font)
        self.IPInput2.setStyleSheet("border: 1px solid rgb(107, 107, 107); \n"
"color: white;")
        self.IPInput2.setObjectName("IPInput2")
        self.tabWidget.addTab(self.RegisterTab, "")
        self.stackedWidget.addWidget(self.LogRegPage)
        self.ForgotPage = QtWidgets.QWidget()
        self.ForgotPage.setObjectName("ForgotPage")
        self.stackedWidget.addWidget(self.ForgotPage)
        self.ChatPage = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Chathura")
        font.setPointSize(36)
        self.ChatPage.setFont(font)
        self.ChatPage.setObjectName("ChatPage")
        self.MessageInput = QtWidgets.QLineEdit(self.ChatPage)
        self.MessageInput.setGeometry(QtCore.QRect(20, 670, 911, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MessageInput.setFont(font)
        self.MessageInput.setStyleSheet("QLineEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-radius: 4px;\n"
"    border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0                     rgb(250, 76, 255), stop:1 rgb(74, 252, 255));\n"
"    color: white;\n"
"}")
        self.MessageInput.setObjectName("MessageInput")
        self.MessagesPlainTextEdit = QtWidgets.QPlainTextEdit(self.ChatPage)
        self.MessagesPlainTextEdit.setGeometry(QtCore.QRect(20, 10, 911, 651))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.MessagesPlainTextEdit.setFont(font)
        self.MessagesPlainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-radius: 4px;\n"
"    border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0                     rgb(250, 76, 255), stop:1 rgb(74, 252, 255));\n"
"    color: white;\n"
"}")
        self.MessagesPlainTextEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MessagesPlainTextEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MessagesPlainTextEdit.setLineWidth(1)
        self.MessagesPlainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.MessagesPlainTextEdit.setUndoRedoEnabled(False)
        self.MessagesPlainTextEdit.setReadOnly(True)
        self.MessagesPlainTextEdit.setPlainText("")
        self.MessagesPlainTextEdit.setCursorWidth(1)
        self.MessagesPlainTextEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.MessagesPlainTextEdit.setPlaceholderText("No chat messages yet! Be the first one to chat?")
        self.MessagesPlainTextEdit.setObjectName("MessagesPlainTextEdit")
        self.VerticalSplitterLine = QtWidgets.QFrame(self.ChatPage)
        self.VerticalSplitterLine.setGeometry(QtCore.QRect(940, -10, 20, 771))
        self.VerticalSplitterLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.VerticalSplitterLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.VerticalSplitterLine.setObjectName("VerticalSplitterLine")
        self.ChannelNameLabel = QtWidgets.QLabel(self.ChatPage)
        self.ChannelNameLabel.setGeometry(QtCore.QRect(960, 10, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Barbaro")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.ChannelNameLabel.setFont(font)
        self.ChannelNameLabel.setStyleSheet("color: rgb(83, 203, 189)")
        self.ChannelNameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.ChannelNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ChannelNameLabel.setWordWrap(False)
        self.ChannelNameLabel.setObjectName("ChannelNameLabel")
        self.OnlineLabel = QtWidgets.QLabel(self.ChatPage)
        self.OnlineLabel.setGeometry(QtCore.QRect(1040, 160, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Brela")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.OnlineLabel.setFont(font)
        self.OnlineLabel.setStyleSheet("color: rgb(83, 203, 189)")
        self.OnlineLabel.setTextFormat(QtCore.Qt.AutoText)
        self.OnlineLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OnlineLabel.setWordWrap(False)
        self.OnlineLabel.setObjectName("OnlineLabel")
        self.OnlineListWidget = QtWidgets.QListWidget(self.ChatPage)
        self.OnlineListWidget.setGeometry(QtCore.QRect(970, 230, 291, 471))
        font = QtGui.QFont()
        font.setFamily("Quattrocento Sans")
        font.setPointSize(16)
        self.OnlineListWidget.setFont(font)
        self.OnlineListWidget.setStyleSheet("QListWidget {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-radius: 4px;\n"
"    border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0                     rgb(250, 76, 255), stop:1 rgb(74, 252, 255));\n"
"    color: white;\n"
"}")
        self.OnlineListWidget.setObjectName("OnlineListWidget")
        self.stackedWidget.addWidget(self.ChatPage)
        self.ChannelsPage = QtWidgets.QWidget()
        self.ChannelsPage.setObjectName("ChannelsPage")
        self.stackedWidget.addWidget(self.ChannelsPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WhiteHat Chat"))
        self.TitleLabel.setText(_translate("MainWindow", "WhiteHat Chat"))
        self.UsernameInput.setPlaceholderText(_translate("MainWindow", "Username"))
        self.PasswordInput.setPlaceholderText(_translate("MainWindow", "Password"))
        self.LoginButton.setText(_translate("MainWindow", "LOG IN"))
        self.ForgotButton.setText(_translate("MainWindow", "Forgot your password?"))
        self.IPInput.setPlaceholderText(_translate("MainWindow", "IP Address"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LoginTab), _translate("MainWindow", "Login"))
        self.UsernameInput2.setPlaceholderText(_translate("MainWindow", "Username"))
        self.PasswordInput2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.NicknameInput.setPlaceholderText(_translate("MainWindow", "Nickname"))
        self.RegisterButton.setText(_translate("MainWindow", "REGISTER"))
        self.IPInput2.setPlaceholderText(_translate("MainWindow", "IP Address"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RegisterTab), _translate("MainWindow", "Register"))
        self.MessageInput.setPlaceholderText(_translate("MainWindow", "Message"))
        self.ChannelNameLabel.setText(_translate("MainWindow", "Place Holder"))
        self.OnlineLabel.setText(_translate("MainWindow", "Online"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

